# Generated by Django 3.1.5 on 2021-01-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiv_recipe',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='indiv_recipe',
            name='ingredient',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
