# Generated by Django 3.1.5 on 2021-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210110_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_recipe',
            name='name',
            field=models.CharField(default='this is food', max_length=100, unique=True),
        ),
    ]
