# Generated by Django 3.1.5 on 2021-01-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210110_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_recipe',
            name='ingredient',
            field=models.TextField(),
        ),
    ]
