# Generated by Django 3.1.5 on 2021-01-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210110_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='indiv_recipe',
            name='vegan',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
