# Generated by Django 3.1.5 on 2021-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_indiv_recipe_vegan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_recipe',
            name='ingredient',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indiv_recipe',
            name='name',
            field=models.CharField(blank=True, default='this is food', max_length=100, unique=True),
        ),
    ]
