# Generated by Django 3.1.5 on 2021-01-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20210110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indiv_recipe',
            name='ingredient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indiv_recipe',
            name='name',
            field=models.CharField(default='this is food', max_length=100, unique=True),
        ),
    ]
