# Generated by Django 3.1.5 on 2021-01-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210110_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiv_recipe',
            name='vegan',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
